
name: Build and Publish Docker Image

on:
  
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          architectures: ${{ matrix.architecture }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Container to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tweb_build
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            hypertext6060/tweb-nginx:${{ steps.date.outputs.today }}
            hypertext6060/tweb-nginx:latest
          